services:
  back:
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./back:/back
    restart: always
    command: php artisan serve --host 0.0.0.0
  worker:
    build: ./
    volumes:
      - ./back:/back
    restart: always
    command: php artisan queue:work
